name: Scrape BCRA Rates Daily

on:
  schedule:
    # Corre todos los días a las 10:00 AM hora Argentina (ART, UTC-3)
    # Esto es 13:00 UTC. Ajusta el cron si necesitas otra hora.
    - cron: '0 13 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions de GitHub

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para que el workflow pueda hacer commit al repositorio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # O la versión de Python que usa tu script

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper to generate tasas_bancos.json
        # ESTA ES LA LÍNEA CLAVE: Asegúrate que el nombre del archivo es EXACTO
        run: python "PRUEBA SCRAP.py" 

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add tasas_bancos.json # El archivo que tu script "PRUEBA SCRAP.py" genera
          if git diff --staged --quiet; then
            echo "No changes to tasas_bancos.json to commit."
          else
            git commit -m "บอท: Actualización diaria de tasas de Plazos Fijos BCRA"
            git push
            echo "tasas_bancos.json actualizado y subido al repositorio."
          fi
