name: Scrape BCRA Rates Daily

on:
  schedule:
    # Corre todos los días a las 10:00 AM hora Argentina (ART, UTC-3)
    # Esto es 13:00 UTC
    - cron: '0 13 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions de GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Puedes usar una versión más reciente si lo deseas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python "PRUEBA SCRAP.py"

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Añadir el archivo JSON de tasas. Si scraper.py no pudo generar el archivo,
          # este comando podría fallar si el archivo no existe.
          # El script scraper.py ahora crea un json vacío en caso de error de scraping.
          git add tasas_bancos.json
          # Comprobar si hay cambios para commitear
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "บอท: Actualización diaria de tasas de Plazos Fijos BCRA"
            # Forzar push para simplificar, asumiendo que este bot es el único que actualiza este archivo.
            # Considerar estrategias más complejas si hay otros commits concurrentes.
            git push
            echo "Tasas actualizadas y subidas al repositorio."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token provisto por GitHub Actions
