name: Scrape Daily Financial Data

on:
  schedule:
    # Corre todos los días a las 10:00 AM hora Argentina (ART, UTC-3)
    - cron: '0 13 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Plazo Fijo Scraper
        run: python "PRUEBA SCRAP.py"

      - name: Run FCI Scraper
        run: python "fci_scraper.py" # Ejecutar el nuevo script

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Añadir AMBOS archivos JSON al commit
          git add tasas_bancos.json fci_data.json
          
          if git diff --staged --quiet; then
            echo "No changes to data files to commit."
          else
            git commit -m "บอท: Actualización diaria de datos financieros (PF y FCI)"
            git push
            echo "Archivos de datos actualizados y subidos al repositorio."
          fi
